### ISSUE TITLE
`Prior` should not be named prior?

### ISSUE THREAD

**Issue by Quba1** [nestordemeure/gaussian_process#55]
I need to say this is a great library and thanks for making GPs available in Rust!

I'm wondering about one thing - should `Prior` be named as it is, because I find it a little bit confusing.

I have a very basic knowledge about GPs and in sources I have read prior is an MVN with some mean and covariance specified by kernel. Graphically this is usually represented as many random "kernelized" functions. And during GP training only those functions are selected that fit training input. Like in this example:

![GP example](https://scikit-learn.org/stable/_images/sphx_glr_plot_gpr_prior_posterior_001.png)

But this is not how `Prior` works as it is simply added to GP prediction:

```rust
/* gaussian_process/mod.rs:240 */

// weights.transpose() * &self.training_outputs + prior
prior.gemm_tr(1f64, &weights, &self.training_outputs.as_vector(), 1f64);
```

To me as a beginner the name `Prior` was very confusing as I couldn't understand for quite a while what `Prior` exactly does, until I found the bit of code above.

As I understand its purpose now, I think `Prior` is a very cool feature (not present in scikit for example) just the naming is a little bit confusing.

So I wonder whether `Prior` could be renamed to for example `Background` or `Base`? And docs could explain its purpose more precisely.

I'm happy to make a PR for this change if you find it worth introducing.

**Comment by nestordemeure** [comment]
I do agree that `Prior` can be hard to understand as we are not talking about the prior *distribution* but rather the prior on the value the function will take if we have no data. The proper technical term would be the **mean function** of the Gaussian process.

Most implementations default to a mean function of zero which means that, far from known points, they return 0. To my mind, this is a problematic behavior (and no a particularly meaningful one, most function do not have a base value of 0), especially if it is not made explicit to users of the library.

I would be open to a PR updating `Prior` to `MeanFunction` in the code and insuring the proper vocabulary is used in all the code base (readme, comments, etc.)
